# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:

  relayer1:
    container_name: relayer1
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_1.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer2:
    container_name: relayer2
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_2.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer3:
    container_name: relayer3
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_3.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer4:
    container_name: relayer4
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_4.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer5:
    container_name: relayer5
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_5.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer6:
    container_name: relayer6
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_6.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer7:
    container_name: relayer7
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_7.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer8:
    container_name: relayer8
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_8.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer9:
    container_name: relayer9
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_9.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer10:
    container_name: relayer10
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      run --config /cfg/config_evm-evm_10.json --latest
    volumes:
      - ./cfg:/cfg
    restart: always

  # otel-collector:
  #   container_name: otel-collector
  #   image: otel/opentelemetry-collector
  #   command: ["--config=/etc/otel-collector-config.yml"]
  #   volumes:
  #     - ./cfg/otel-collector-config.yml:/etc/otel-collector-config.yml
  #   ports:
  #     - "8889:8889"   # Prometheus exporter metrics