# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:

  relayer1:
    container_name: relayer1
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command:
      #/etc/init.d/tor start && /bridge run --config /cfg/config_evm-evm_1.json --latest
      /bin/sh -c "/etc/init.d/tor start && /bridge run --config /cfg/config_evm-evm_1.json --latest"

    volumes:
      - ./cfg:/cfg
    #environment:
    #  - NODE_TLS_REJECT_UNAUTHORIZED=0
    # ports:
    #   - "9050"

  # relayer2:
  #   container_name: relayer2
  #   build:
  #     context: ../.
  #     dockerfile: ./example/Dockerfile
  #   command: run --config /cfg/config_evm-evm_2.json --latest
  #   volumes:
  #     - ./cfg:/cfg
  #   restart: always

  # relayer3:
  #   container_name: relayer3
  #   build:
  #     context: ../.
  #     dockerfile: ./example/Dockerfile
  #   command: run --config /cfg/config_evm-evm_3.json --latest
  #   volumes:
  #     - ./cfg:/cfg
  #   restart: always

  # otel-collector:
  #   container_name: otel-collector
  #   image: otel/opentelemetry-collector
  #   command: ["--config=/etc/otel-collector-config.yml"]
  #   volumes:
  #     - ./cfg/otel-collector-config.yml:/etc/otel-collector-config.yml
  #   ports:
  #     - "8889:8889"   # Prometheus exporter metrics