receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 1000
    send_batch_size: 100

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true

  prometheus:
    endpoint: "otel-collector:8889"
    namespace: relayer
    send_timestamps: true
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200


service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors:  [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]