receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default
  jaeger:
    endpoint: 0.0.0.0:14250

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      exporters: [prometheus]
      receivers: [otlp]
    traces:
      receivers: [otlp]
      exporters: [jaeger]