name: Update ChainBridge core-example

on:
  push:
    branches:
      - 'main'

jobs:
  update-core-example:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger chainbridge-core-example update event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_PAM }}
          # Repository to which to dispatch the event
          repository: ChainSafe/chainbridge-core-example
          event-type: push-core-to-main-branch
          client-payload: '{"sha": "${{ github.sha }}"}'
